apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: endpoint
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: endpoint
  template:
    metadata:
      labels:
        app: endpoint
    spec:
      containers:
        - name: endpoint
          # image: bright/endpoint:latest
          image: bright/endpoint:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: service-config
              mountPath: /etc/endpoint
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: mysql_password
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
      volumes:
        - name: service-config
          configMap:
            name: endpoint-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: endpoint
spec:
  ports:
    - name: http
      port: 30100
      targetPort: 30100
    - name: grpc
      port: 30101
      targetPort: 30101
    - name: healthz
      port: 30102
      targetPort: 30102
  selector:
    app: endpoint
