apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kube-system
  name: endpoint-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-endpoint-prefix@kubernetescrd

spec:
  rules:
    - host:
      http:
        paths:
          - path: /api/endpoint/
            pathType: Prefix
            backend:
              service:
                name: endpoint
                port:
                  number: 30120