version="0.0.1"

[contract]
domain="contract"
http-port=30110
grpc-port=30111
log-file="/var/log/contract.log"

[endpoint]
domain="endpoint"
http-port=30120
grpc-port=30121
log-file="/var/log/endpoint.log"

[account]
domain="account"
http-port=30130
grpc-port=30131
log-file="/var/log/account.log"

[datafin]
domain="datafin"
http-port=30140
grpc-port=30141
log-file="/var/log/datafin.log"

[mysql]
domain="mysql-headless"
port=3306
user="root"
password="123456"
database="bright"

[redis]
address="redis-cluster-headless:6379"
password=""

[pulsar]
domain="milvus-pulsar-proxy"
port=6650
operation-timeout=30
connection-timeout=30
topic-sync-task="topic_sync_task"
topic-transform-image="topic_transform_image"

