apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: devbox-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /root
    server: 192.168.18.199

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
