apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 38080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-webui
  namespace: kube-system

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: traefik-webui
