// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"yun.tea/block/bright/datafin/pkg/db/ent/datafin"
	"yun.tea/block/bright/datafin/pkg/db/ent/predicate"
)

// DataFinQuery is the builder for querying DataFin entities.
type DataFinQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DataFin
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DataFinQuery builder.
func (dfq *DataFinQuery) Where(ps ...predicate.DataFin) *DataFinQuery {
	dfq.predicates = append(dfq.predicates, ps...)
	return dfq
}

// Limit adds a limit step to the query.
func (dfq *DataFinQuery) Limit(limit int) *DataFinQuery {
	dfq.limit = &limit
	return dfq
}

// Offset adds an offset step to the query.
func (dfq *DataFinQuery) Offset(offset int) *DataFinQuery {
	dfq.offset = &offset
	return dfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dfq *DataFinQuery) Unique(unique bool) *DataFinQuery {
	dfq.unique = &unique
	return dfq
}

// Order adds an order step to the query.
func (dfq *DataFinQuery) Order(o ...OrderFunc) *DataFinQuery {
	dfq.order = append(dfq.order, o...)
	return dfq
}

// First returns the first DataFin entity from the query.
// Returns a *NotFoundError when no DataFin was found.
func (dfq *DataFinQuery) First(ctx context.Context) (*DataFin, error) {
	nodes, err := dfq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{datafin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dfq *DataFinQuery) FirstX(ctx context.Context) *DataFin {
	node, err := dfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DataFin ID from the query.
// Returns a *NotFoundError when no DataFin ID was found.
func (dfq *DataFinQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dfq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{datafin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dfq *DataFinQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DataFin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DataFin entity is found.
// Returns a *NotFoundError when no DataFin entities are found.
func (dfq *DataFinQuery) Only(ctx context.Context) (*DataFin, error) {
	nodes, err := dfq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{datafin.Label}
	default:
		return nil, &NotSingularError{datafin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dfq *DataFinQuery) OnlyX(ctx context.Context) *DataFin {
	node, err := dfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DataFin ID in the query.
// Returns a *NotSingularError when more than one DataFin ID is found.
// Returns a *NotFoundError when no entities are found.
func (dfq *DataFinQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dfq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{datafin.Label}
	default:
		err = &NotSingularError{datafin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dfq *DataFinQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DataFins.
func (dfq *DataFinQuery) All(ctx context.Context) ([]*DataFin, error) {
	if err := dfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dfq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dfq *DataFinQuery) AllX(ctx context.Context) []*DataFin {
	nodes, err := dfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DataFin IDs.
func (dfq *DataFinQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := dfq.Select(datafin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dfq *DataFinQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dfq *DataFinQuery) Count(ctx context.Context) (int, error) {
	if err := dfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dfq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dfq *DataFinQuery) CountX(ctx context.Context) int {
	count, err := dfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dfq *DataFinQuery) Exist(ctx context.Context) (bool, error) {
	if err := dfq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dfq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dfq *DataFinQuery) ExistX(ctx context.Context) bool {
	exist, err := dfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DataFinQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dfq *DataFinQuery) Clone() *DataFinQuery {
	if dfq == nil {
		return nil
	}
	return &DataFinQuery{
		config:     dfq.config,
		limit:      dfq.limit,
		offset:     dfq.offset,
		order:      append([]OrderFunc{}, dfq.order...),
		predicates: append([]predicate.DataFin{}, dfq.predicates...),
		// clone intermediate query.
		sql:    dfq.sql.Clone(),
		path:   dfq.path,
		unique: dfq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DataFin.Query().
//		GroupBy(datafin.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dfq *DataFinQuery) GroupBy(field string, fields ...string) *DataFinGroupBy {
	grbuild := &DataFinGroupBy{config: dfq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dfq.sqlQuery(ctx), nil
	}
	grbuild.label = datafin.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.DataFin.Query().
//		Select(datafin.FieldCreatedAt).
//		Scan(ctx, &v)
func (dfq *DataFinQuery) Select(fields ...string) *DataFinSelect {
	dfq.fields = append(dfq.fields, fields...)
	selbuild := &DataFinSelect{DataFinQuery: dfq}
	selbuild.label = datafin.Label
	selbuild.flds, selbuild.scan = &dfq.fields, selbuild.Scan
	return selbuild
}

func (dfq *DataFinQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dfq.fields {
		if !datafin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dfq.path != nil {
		prev, err := dfq.path(ctx)
		if err != nil {
			return err
		}
		dfq.sql = prev
	}
	if datafin.Policy == nil {
		return errors.New("ent: uninitialized datafin.Policy (forgotten import ent/runtime?)")
	}
	if err := datafin.Policy.EvalQuery(ctx, dfq); err != nil {
		return err
	}
	return nil
}

func (dfq *DataFinQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DataFin, error) {
	var (
		nodes = []*DataFin{}
		_spec = dfq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*DataFin).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &DataFin{config: dfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(dfq.modifiers) > 0 {
		_spec.Modifiers = dfq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (dfq *DataFinQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dfq.querySpec()
	if len(dfq.modifiers) > 0 {
		_spec.Modifiers = dfq.modifiers
	}
	_spec.Node.Columns = dfq.fields
	if len(dfq.fields) > 0 {
		_spec.Unique = dfq.unique != nil && *dfq.unique
	}
	return sqlgraph.CountNodes(ctx, dfq.driver, _spec)
}

func (dfq *DataFinQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dfq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dfq *DataFinQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   datafin.Table,
			Columns: datafin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: datafin.FieldID,
			},
		},
		From:   dfq.sql,
		Unique: true,
	}
	if unique := dfq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dfq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datafin.FieldID)
		for i := range fields {
			if fields[i] != datafin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dfq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dfq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dfq *DataFinQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dfq.driver.Dialect())
	t1 := builder.Table(datafin.Table)
	columns := dfq.fields
	if len(columns) == 0 {
		columns = datafin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dfq.sql != nil {
		selector = dfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dfq.unique != nil && *dfq.unique {
		selector.Distinct()
	}
	for _, m := range dfq.modifiers {
		m(selector)
	}
	for _, p := range dfq.predicates {
		p(selector)
	}
	for _, p := range dfq.order {
		p(selector)
	}
	if offset := dfq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dfq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (dfq *DataFinQuery) ForUpdate(opts ...sql.LockOption) *DataFinQuery {
	if dfq.driver.Dialect() == dialect.Postgres {
		dfq.Unique(false)
	}
	dfq.modifiers = append(dfq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return dfq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (dfq *DataFinQuery) ForShare(opts ...sql.LockOption) *DataFinQuery {
	if dfq.driver.Dialect() == dialect.Postgres {
		dfq.Unique(false)
	}
	dfq.modifiers = append(dfq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return dfq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dfq *DataFinQuery) Modify(modifiers ...func(s *sql.Selector)) *DataFinSelect {
	dfq.modifiers = append(dfq.modifiers, modifiers...)
	return dfq.Select()
}

// DataFinGroupBy is the group-by builder for DataFin entities.
type DataFinGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dfgb *DataFinGroupBy) Aggregate(fns ...AggregateFunc) *DataFinGroupBy {
	dfgb.fns = append(dfgb.fns, fns...)
	return dfgb
}

// Scan applies the group-by query and scans the result into the given value.
func (dfgb *DataFinGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dfgb.path(ctx)
	if err != nil {
		return err
	}
	dfgb.sql = query
	return dfgb.sqlScan(ctx, v)
}

func (dfgb *DataFinGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dfgb.fields {
		if !datafin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dfgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dfgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dfgb *DataFinGroupBy) sqlQuery() *sql.Selector {
	selector := dfgb.sql.Select()
	aggregation := make([]string, 0, len(dfgb.fns))
	for _, fn := range dfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dfgb.fields)+len(dfgb.fns))
		for _, f := range dfgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dfgb.fields...)...)
}

// DataFinSelect is the builder for selecting fields of DataFin entities.
type DataFinSelect struct {
	*DataFinQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dfs *DataFinSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dfs.prepareQuery(ctx); err != nil {
		return err
	}
	dfs.sql = dfs.DataFinQuery.sqlQuery(ctx)
	return dfs.sqlScan(ctx, v)
}

func (dfs *DataFinSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dfs.sql.Query()
	if err := dfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dfs *DataFinSelect) Modify(modifiers ...func(s *sql.Selector)) *DataFinSelect {
	dfs.modifiers = append(dfs.modifiers, modifiers...)
	return dfs
}
