// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"yun.tea/block/bright/datafin/pkg/db/ent/filerecord"
	"yun.tea/block/bright/datafin/pkg/db/ent/predicate"
)

// FileRecordUpdate is the builder for updating FileRecord entities.
type FileRecordUpdate struct {
	config
	hooks     []Hook
	mutation  *FileRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FileRecordUpdate builder.
func (fru *FileRecordUpdate) Where(ps ...predicate.FileRecord) *FileRecordUpdate {
	fru.mutation.Where(ps...)
	return fru
}

// SetCreatedAt sets the "created_at" field.
func (fru *FileRecordUpdate) SetCreatedAt(u uint32) *FileRecordUpdate {
	fru.mutation.ResetCreatedAt()
	fru.mutation.SetCreatedAt(u)
	return fru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fru *FileRecordUpdate) SetNillableCreatedAt(u *uint32) *FileRecordUpdate {
	if u != nil {
		fru.SetCreatedAt(*u)
	}
	return fru
}

// AddCreatedAt adds u to the "created_at" field.
func (fru *FileRecordUpdate) AddCreatedAt(u int32) *FileRecordUpdate {
	fru.mutation.AddCreatedAt(u)
	return fru
}

// SetUpdatedAt sets the "updated_at" field.
func (fru *FileRecordUpdate) SetUpdatedAt(u uint32) *FileRecordUpdate {
	fru.mutation.ResetUpdatedAt()
	fru.mutation.SetUpdatedAt(u)
	return fru
}

// AddUpdatedAt adds u to the "updated_at" field.
func (fru *FileRecordUpdate) AddUpdatedAt(u int32) *FileRecordUpdate {
	fru.mutation.AddUpdatedAt(u)
	return fru
}

// SetDeletedAt sets the "deleted_at" field.
func (fru *FileRecordUpdate) SetDeletedAt(u uint32) *FileRecordUpdate {
	fru.mutation.ResetDeletedAt()
	fru.mutation.SetDeletedAt(u)
	return fru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fru *FileRecordUpdate) SetNillableDeletedAt(u *uint32) *FileRecordUpdate {
	if u != nil {
		fru.SetDeletedAt(*u)
	}
	return fru
}

// AddDeletedAt adds u to the "deleted_at" field.
func (fru *FileRecordUpdate) AddDeletedAt(u int32) *FileRecordUpdate {
	fru.mutation.AddDeletedAt(u)
	return fru
}

// SetFileName sets the "file_name" field.
func (fru *FileRecordUpdate) SetFileName(s string) *FileRecordUpdate {
	fru.mutation.SetFileName(s)
	return fru
}

// SetTopicID sets the "topic_id" field.
func (fru *FileRecordUpdate) SetTopicID(s string) *FileRecordUpdate {
	fru.mutation.SetTopicID(s)
	return fru
}

// SetRecordNum sets the "record_num" field.
func (fru *FileRecordUpdate) SetRecordNum(u uint32) *FileRecordUpdate {
	fru.mutation.ResetRecordNum()
	fru.mutation.SetRecordNum(u)
	return fru
}

// SetNillableRecordNum sets the "record_num" field if the given value is not nil.
func (fru *FileRecordUpdate) SetNillableRecordNum(u *uint32) *FileRecordUpdate {
	if u != nil {
		fru.SetRecordNum(*u)
	}
	return fru
}

// AddRecordNum adds u to the "record_num" field.
func (fru *FileRecordUpdate) AddRecordNum(u int32) *FileRecordUpdate {
	fru.mutation.AddRecordNum(u)
	return fru
}

// SetSha1Sum sets the "sha1_sum" field.
func (fru *FileRecordUpdate) SetSha1Sum(s string) *FileRecordUpdate {
	fru.mutation.SetSha1Sum(s)
	return fru
}

// SetState sets the "state" field.
func (fru *FileRecordUpdate) SetState(s string) *FileRecordUpdate {
	fru.mutation.SetState(s)
	return fru
}

// SetRemark sets the "remark" field.
func (fru *FileRecordUpdate) SetRemark(s string) *FileRecordUpdate {
	fru.mutation.SetRemark(s)
	return fru
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (fru *FileRecordUpdate) SetNillableRemark(s *string) *FileRecordUpdate {
	if s != nil {
		fru.SetRemark(*s)
	}
	return fru
}

// ClearRemark clears the value of the "remark" field.
func (fru *FileRecordUpdate) ClearRemark() *FileRecordUpdate {
	fru.mutation.ClearRemark()
	return fru
}

// Mutation returns the FileRecordMutation object of the builder.
func (fru *FileRecordUpdate) Mutation() *FileRecordMutation {
	return fru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fru *FileRecordUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := fru.defaults(); err != nil {
		return 0, err
	}
	if len(fru.hooks) == 0 {
		affected, err = fru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fru.mutation = mutation
			affected, err = fru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fru.hooks) - 1; i >= 0; i-- {
			if fru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fru *FileRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := fru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fru *FileRecordUpdate) Exec(ctx context.Context) error {
	_, err := fru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fru *FileRecordUpdate) ExecX(ctx context.Context) {
	if err := fru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fru *FileRecordUpdate) defaults() error {
	if _, ok := fru.mutation.UpdatedAt(); !ok {
		if filerecord.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized filerecord.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := filerecord.UpdateDefaultUpdatedAt()
		fru.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (fru *FileRecordUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FileRecordUpdate {
	fru.modifiers = append(fru.modifiers, modifiers...)
	return fru
}

func (fru *FileRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   filerecord.Table,
			Columns: filerecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: filerecord.FieldID,
			},
		},
	}
	if ps := fru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fru.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldCreatedAt,
		})
	}
	if value, ok := fru.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldCreatedAt,
		})
	}
	if value, ok := fru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldUpdatedAt,
		})
	}
	if value, ok := fru.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldUpdatedAt,
		})
	}
	if value, ok := fru.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldDeletedAt,
		})
	}
	if value, ok := fru.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldDeletedAt,
		})
	}
	if value, ok := fru.mutation.FileName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldFileName,
		})
	}
	if value, ok := fru.mutation.TopicID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldTopicID,
		})
	}
	if value, ok := fru.mutation.RecordNum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldRecordNum,
		})
	}
	if value, ok := fru.mutation.AddedRecordNum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldRecordNum,
		})
	}
	if value, ok := fru.mutation.Sha1Sum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldSha1Sum,
		})
	}
	if value, ok := fru.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldState,
		})
	}
	if value, ok := fru.mutation.Remark(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldRemark,
		})
	}
	if fru.mutation.RemarkCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: filerecord.FieldRemark,
		})
	}
	_spec.Modifiers = fru.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, fru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// FileRecordUpdateOne is the builder for updating a single FileRecord entity.
type FileRecordUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FileRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (fruo *FileRecordUpdateOne) SetCreatedAt(u uint32) *FileRecordUpdateOne {
	fruo.mutation.ResetCreatedAt()
	fruo.mutation.SetCreatedAt(u)
	return fruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fruo *FileRecordUpdateOne) SetNillableCreatedAt(u *uint32) *FileRecordUpdateOne {
	if u != nil {
		fruo.SetCreatedAt(*u)
	}
	return fruo
}

// AddCreatedAt adds u to the "created_at" field.
func (fruo *FileRecordUpdateOne) AddCreatedAt(u int32) *FileRecordUpdateOne {
	fruo.mutation.AddCreatedAt(u)
	return fruo
}

// SetUpdatedAt sets the "updated_at" field.
func (fruo *FileRecordUpdateOne) SetUpdatedAt(u uint32) *FileRecordUpdateOne {
	fruo.mutation.ResetUpdatedAt()
	fruo.mutation.SetUpdatedAt(u)
	return fruo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (fruo *FileRecordUpdateOne) AddUpdatedAt(u int32) *FileRecordUpdateOne {
	fruo.mutation.AddUpdatedAt(u)
	return fruo
}

// SetDeletedAt sets the "deleted_at" field.
func (fruo *FileRecordUpdateOne) SetDeletedAt(u uint32) *FileRecordUpdateOne {
	fruo.mutation.ResetDeletedAt()
	fruo.mutation.SetDeletedAt(u)
	return fruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fruo *FileRecordUpdateOne) SetNillableDeletedAt(u *uint32) *FileRecordUpdateOne {
	if u != nil {
		fruo.SetDeletedAt(*u)
	}
	return fruo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (fruo *FileRecordUpdateOne) AddDeletedAt(u int32) *FileRecordUpdateOne {
	fruo.mutation.AddDeletedAt(u)
	return fruo
}

// SetFileName sets the "file_name" field.
func (fruo *FileRecordUpdateOne) SetFileName(s string) *FileRecordUpdateOne {
	fruo.mutation.SetFileName(s)
	return fruo
}

// SetTopicID sets the "topic_id" field.
func (fruo *FileRecordUpdateOne) SetTopicID(s string) *FileRecordUpdateOne {
	fruo.mutation.SetTopicID(s)
	return fruo
}

// SetRecordNum sets the "record_num" field.
func (fruo *FileRecordUpdateOne) SetRecordNum(u uint32) *FileRecordUpdateOne {
	fruo.mutation.ResetRecordNum()
	fruo.mutation.SetRecordNum(u)
	return fruo
}

// SetNillableRecordNum sets the "record_num" field if the given value is not nil.
func (fruo *FileRecordUpdateOne) SetNillableRecordNum(u *uint32) *FileRecordUpdateOne {
	if u != nil {
		fruo.SetRecordNum(*u)
	}
	return fruo
}

// AddRecordNum adds u to the "record_num" field.
func (fruo *FileRecordUpdateOne) AddRecordNum(u int32) *FileRecordUpdateOne {
	fruo.mutation.AddRecordNum(u)
	return fruo
}

// SetSha1Sum sets the "sha1_sum" field.
func (fruo *FileRecordUpdateOne) SetSha1Sum(s string) *FileRecordUpdateOne {
	fruo.mutation.SetSha1Sum(s)
	return fruo
}

// SetState sets the "state" field.
func (fruo *FileRecordUpdateOne) SetState(s string) *FileRecordUpdateOne {
	fruo.mutation.SetState(s)
	return fruo
}

// SetRemark sets the "remark" field.
func (fruo *FileRecordUpdateOne) SetRemark(s string) *FileRecordUpdateOne {
	fruo.mutation.SetRemark(s)
	return fruo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (fruo *FileRecordUpdateOne) SetNillableRemark(s *string) *FileRecordUpdateOne {
	if s != nil {
		fruo.SetRemark(*s)
	}
	return fruo
}

// ClearRemark clears the value of the "remark" field.
func (fruo *FileRecordUpdateOne) ClearRemark() *FileRecordUpdateOne {
	fruo.mutation.ClearRemark()
	return fruo
}

// Mutation returns the FileRecordMutation object of the builder.
func (fruo *FileRecordUpdateOne) Mutation() *FileRecordMutation {
	return fruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fruo *FileRecordUpdateOne) Select(field string, fields ...string) *FileRecordUpdateOne {
	fruo.fields = append([]string{field}, fields...)
	return fruo
}

// Save executes the query and returns the updated FileRecord entity.
func (fruo *FileRecordUpdateOne) Save(ctx context.Context) (*FileRecord, error) {
	var (
		err  error
		node *FileRecord
	)
	if err := fruo.defaults(); err != nil {
		return nil, err
	}
	if len(fruo.hooks) == 0 {
		node, err = fruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fruo.mutation = mutation
			node, err = fruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fruo.hooks) - 1; i >= 0; i-- {
			if fruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FileRecord)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FileRecordMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fruo *FileRecordUpdateOne) SaveX(ctx context.Context) *FileRecord {
	node, err := fruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fruo *FileRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := fruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fruo *FileRecordUpdateOne) ExecX(ctx context.Context) {
	if err := fruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fruo *FileRecordUpdateOne) defaults() error {
	if _, ok := fruo.mutation.UpdatedAt(); !ok {
		if filerecord.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized filerecord.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := filerecord.UpdateDefaultUpdatedAt()
		fruo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (fruo *FileRecordUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FileRecordUpdateOne {
	fruo.modifiers = append(fruo.modifiers, modifiers...)
	return fruo
}

func (fruo *FileRecordUpdateOne) sqlSave(ctx context.Context) (_node *FileRecord, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   filerecord.Table,
			Columns: filerecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: filerecord.FieldID,
			},
		},
	}
	id, ok := fruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filerecord.FieldID)
		for _, f := range fields {
			if !filerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fruo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldCreatedAt,
		})
	}
	if value, ok := fruo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldCreatedAt,
		})
	}
	if value, ok := fruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldUpdatedAt,
		})
	}
	if value, ok := fruo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldUpdatedAt,
		})
	}
	if value, ok := fruo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldDeletedAt,
		})
	}
	if value, ok := fruo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldDeletedAt,
		})
	}
	if value, ok := fruo.mutation.FileName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldFileName,
		})
	}
	if value, ok := fruo.mutation.TopicID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldTopicID,
		})
	}
	if value, ok := fruo.mutation.RecordNum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldRecordNum,
		})
	}
	if value, ok := fruo.mutation.AddedRecordNum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: filerecord.FieldRecordNum,
		})
	}
	if value, ok := fruo.mutation.Sha1Sum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldSha1Sum,
		})
	}
	if value, ok := fruo.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldState,
		})
	}
	if value, ok := fruo.mutation.Remark(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filerecord.FieldRemark,
		})
	}
	if fruo.mutation.RemarkCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: filerecord.FieldRemark,
		})
	}
	_spec.Modifiers = fruo.modifiers
	_node = &FileRecord{config: fruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
