// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DataFinsColumns holds the columns for the "data_fins" table.
	DataFinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "topic_id", Type: field.TypeString},
		{Name: "data_id", Type: field.TypeString},
		{Name: "datafin", Type: field.TypeString},
		{Name: "tx_time", Type: field.TypeUint32, Nullable: true},
		{Name: "tx_hash", Type: field.TypeString, Nullable: true},
		{Name: "state", Type: field.TypeString},
		{Name: "retries", Type: field.TypeUint32},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// DataFinsTable holds the schema information for the "data_fins" table.
	DataFinsTable = &schema.Table{
		Name:       "data_fins",
		Columns:    DataFinsColumns,
		PrimaryKey: []*schema.Column{DataFinsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "datafin_topic_id_data_id",
				Unique:  false,
				Columns: []*schema.Column{DataFinsColumns[4], DataFinsColumns[5]},
			},
			{
				Name:    "datafin_created_at",
				Unique:  false,
				Columns: []*schema.Column{DataFinsColumns[1]},
			},
		},
	}
	// FileRecordsColumns holds the columns for the "file_records" table.
	FileRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "file_name", Type: field.TypeString},
		{Name: "topic_id", Type: field.TypeString},
		{Name: "record_num", Type: field.TypeUint32, Default: 0},
		{Name: "sha1_sum", Type: field.TypeString},
		{Name: "state", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// FileRecordsTable holds the schema information for the "file_records" table.
	FileRecordsTable = &schema.Table{
		Name:       "file_records",
		Columns:    FileRecordsColumns,
		PrimaryKey: []*schema.Column{FileRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "filerecord_file_name",
				Unique:  false,
				Columns: []*schema.Column{FileRecordsColumns[4]},
			},
			{
				Name:    "filerecord_topic_id",
				Unique:  false,
				Columns: []*schema.Column{FileRecordsColumns[5]},
			},
			{
				Name:    "filerecord_created_at",
				Unique:  false,
				Columns: []*schema.Column{FileRecordsColumns[1]},
			},
		},
	}
	// MqueuesColumns holds the columns for the "mqueues" table.
	MqueuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "topic_name", Type: field.TypeString, Unique: true},
	}
	// MqueuesTable holds the schema information for the "mqueues" table.
	MqueuesTable = &schema.Table{
		Name:       "mqueues",
		Columns:    MqueuesColumns,
		PrimaryKey: []*schema.Column{MqueuesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mqueue_created_at",
				Unique:  false,
				Columns: []*schema.Column{MqueuesColumns[1]},
			},
		},
	}
	// TopicsColumns holds the columns for the "topics" table.
	TopicsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "topic_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "contract", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "change_able", Type: field.TypeBool},
		{Name: "on_chain", Type: field.TypeBool},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// TopicsTable holds the schema information for the "topics" table.
	TopicsTable = &schema.Table{
		Name:       "topics",
		Columns:    TopicsColumns,
		PrimaryKey: []*schema.Column{TopicsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "topic_topic_id_contract",
				Unique:  true,
				Columns: []*schema.Column{TopicsColumns[4], TopicsColumns[6]},
			},
			{
				Name:    "topic_created_at",
				Unique:  false,
				Columns: []*schema.Column{TopicsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DataFinsTable,
		FileRecordsTable,
		MqueuesTable,
		TopicsTable,
	}
)

func init() {
}
