apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: datafin
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datafin
  template:
    metadata:
      labels:
        app: datafin
    spec:
      containers:
        - name: datafin
          # image: bright/datafin:latest
          image: bright/datafin:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: service-config
              mountPath: /etc/datafin
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: mysql_password
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
      volumes:
        - name: service-config
          configMap:
            name: datafin-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: datafin
spec:
  ports:
    - name: http
      port: 30140
      targetPort: 30140
    - name: grpc
      port: 30141
      targetPort: 30141
    - name: healthz
      port: 30142
      targetPort: 30142
  selector:
    app: datafin
