// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"yun.tea/block/bright/account/pkg/db/ent/predicate"
	"yun.tea/block/bright/account/pkg/db/ent/txnum"
)

// TxNumQuery is the builder for querying TxNum entities.
type TxNumQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TxNum
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TxNumQuery builder.
func (tnq *TxNumQuery) Where(ps ...predicate.TxNum) *TxNumQuery {
	tnq.predicates = append(tnq.predicates, ps...)
	return tnq
}

// Limit adds a limit step to the query.
func (tnq *TxNumQuery) Limit(limit int) *TxNumQuery {
	tnq.limit = &limit
	return tnq
}

// Offset adds an offset step to the query.
func (tnq *TxNumQuery) Offset(offset int) *TxNumQuery {
	tnq.offset = &offset
	return tnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tnq *TxNumQuery) Unique(unique bool) *TxNumQuery {
	tnq.unique = &unique
	return tnq
}

// Order adds an order step to the query.
func (tnq *TxNumQuery) Order(o ...OrderFunc) *TxNumQuery {
	tnq.order = append(tnq.order, o...)
	return tnq
}

// First returns the first TxNum entity from the query.
// Returns a *NotFoundError when no TxNum was found.
func (tnq *TxNumQuery) First(ctx context.Context) (*TxNum, error) {
	nodes, err := tnq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{txnum.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tnq *TxNumQuery) FirstX(ctx context.Context) *TxNum {
	node, err := tnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TxNum ID from the query.
// Returns a *NotFoundError when no TxNum ID was found.
func (tnq *TxNumQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = tnq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{txnum.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tnq *TxNumQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := tnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TxNum entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TxNum entity is found.
// Returns a *NotFoundError when no TxNum entities are found.
func (tnq *TxNumQuery) Only(ctx context.Context) (*TxNum, error) {
	nodes, err := tnq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{txnum.Label}
	default:
		return nil, &NotSingularError{txnum.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tnq *TxNumQuery) OnlyX(ctx context.Context) *TxNum {
	node, err := tnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TxNum ID in the query.
// Returns a *NotSingularError when more than one TxNum ID is found.
// Returns a *NotFoundError when no entities are found.
func (tnq *TxNumQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = tnq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{txnum.Label}
	default:
		err = &NotSingularError{txnum.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tnq *TxNumQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := tnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TxNums.
func (tnq *TxNumQuery) All(ctx context.Context) ([]*TxNum, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tnq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tnq *TxNumQuery) AllX(ctx context.Context) []*TxNum {
	nodes, err := tnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TxNum IDs.
func (tnq *TxNumQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := tnq.Select(txnum.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tnq *TxNumQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := tnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tnq *TxNumQuery) Count(ctx context.Context) (int, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tnq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tnq *TxNumQuery) CountX(ctx context.Context) int {
	count, err := tnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tnq *TxNumQuery) Exist(ctx context.Context) (bool, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tnq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tnq *TxNumQuery) ExistX(ctx context.Context) bool {
	exist, err := tnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TxNumQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tnq *TxNumQuery) Clone() *TxNumQuery {
	if tnq == nil {
		return nil
	}
	return &TxNumQuery{
		config:     tnq.config,
		limit:      tnq.limit,
		offset:     tnq.offset,
		order:      append([]OrderFunc{}, tnq.order...),
		predicates: append([]predicate.TxNum{}, tnq.predicates...),
		// clone intermediate query.
		sql:    tnq.sql.Clone(),
		path:   tnq.path,
		unique: tnq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TxNum.Query().
//		GroupBy(txnum.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tnq *TxNumQuery) GroupBy(field string, fields ...string) *TxNumGroupBy {
	grbuild := &TxNumGroupBy{config: tnq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tnq.sqlQuery(ctx), nil
	}
	grbuild.label = txnum.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.TxNum.Query().
//		Select(txnum.FieldCreatedAt).
//		Scan(ctx, &v)
func (tnq *TxNumQuery) Select(fields ...string) *TxNumSelect {
	tnq.fields = append(tnq.fields, fields...)
	selbuild := &TxNumSelect{TxNumQuery: tnq}
	selbuild.label = txnum.Label
	selbuild.flds, selbuild.scan = &tnq.fields, selbuild.Scan
	return selbuild
}

func (tnq *TxNumQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tnq.fields {
		if !txnum.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tnq.path != nil {
		prev, err := tnq.path(ctx)
		if err != nil {
			return err
		}
		tnq.sql = prev
	}
	if txnum.Policy == nil {
		return errors.New("ent: uninitialized txnum.Policy (forgotten import ent/runtime?)")
	}
	if err := txnum.Policy.EvalQuery(ctx, tnq); err != nil {
		return err
	}
	return nil
}

func (tnq *TxNumQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TxNum, error) {
	var (
		nodes = []*TxNum{}
		_spec = tnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TxNum).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TxNum{config: tnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(tnq.modifiers) > 0 {
		_spec.Modifiers = tnq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tnq *TxNumQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tnq.querySpec()
	if len(tnq.modifiers) > 0 {
		_spec.Modifiers = tnq.modifiers
	}
	_spec.Node.Columns = tnq.fields
	if len(tnq.fields) > 0 {
		_spec.Unique = tnq.unique != nil && *tnq.unique
	}
	return sqlgraph.CountNodes(ctx, tnq.driver, _spec)
}

func (tnq *TxNumQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tnq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tnq *TxNumQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   txnum.Table,
			Columns: txnum.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: txnum.FieldID,
			},
		},
		From:   tnq.sql,
		Unique: true,
	}
	if unique := tnq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tnq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, txnum.FieldID)
		for i := range fields {
			if fields[i] != txnum.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tnq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tnq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tnq *TxNumQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tnq.driver.Dialect())
	t1 := builder.Table(txnum.Table)
	columns := tnq.fields
	if len(columns) == 0 {
		columns = txnum.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tnq.sql != nil {
		selector = tnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tnq.unique != nil && *tnq.unique {
		selector.Distinct()
	}
	for _, m := range tnq.modifiers {
		m(selector)
	}
	for _, p := range tnq.predicates {
		p(selector)
	}
	for _, p := range tnq.order {
		p(selector)
	}
	if offset := tnq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tnq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tnq *TxNumQuery) ForUpdate(opts ...sql.LockOption) *TxNumQuery {
	if tnq.driver.Dialect() == dialect.Postgres {
		tnq.Unique(false)
	}
	tnq.modifiers = append(tnq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tnq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tnq *TxNumQuery) ForShare(opts ...sql.LockOption) *TxNumQuery {
	if tnq.driver.Dialect() == dialect.Postgres {
		tnq.Unique(false)
	}
	tnq.modifiers = append(tnq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tnq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tnq *TxNumQuery) Modify(modifiers ...func(s *sql.Selector)) *TxNumSelect {
	tnq.modifiers = append(tnq.modifiers, modifiers...)
	return tnq.Select()
}

// TxNumGroupBy is the group-by builder for TxNum entities.
type TxNumGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tngb *TxNumGroupBy) Aggregate(fns ...AggregateFunc) *TxNumGroupBy {
	tngb.fns = append(tngb.fns, fns...)
	return tngb
}

// Scan applies the group-by query and scans the result into the given value.
func (tngb *TxNumGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tngb.path(ctx)
	if err != nil {
		return err
	}
	tngb.sql = query
	return tngb.sqlScan(ctx, v)
}

func (tngb *TxNumGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tngb.fields {
		if !txnum.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tngb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tngb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tngb *TxNumGroupBy) sqlQuery() *sql.Selector {
	selector := tngb.sql.Select()
	aggregation := make([]string, 0, len(tngb.fns))
	for _, fn := range tngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tngb.fields)+len(tngb.fns))
		for _, f := range tngb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tngb.fields...)...)
}

// TxNumSelect is the builder for selecting fields of TxNum entities.
type TxNumSelect struct {
	*TxNumQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tns *TxNumSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tns.prepareQuery(ctx); err != nil {
		return err
	}
	tns.sql = tns.TxNumQuery.sqlQuery(ctx)
	return tns.sqlScan(ctx, v)
}

func (tns *TxNumSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tns.sql.Query()
	if err := tns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tns *TxNumSelect) Modify(modifiers ...func(s *sql.Selector)) *TxNumSelect {
	tns.modifiers = append(tns.modifiers, modifiers...)
	return tns
}
