FROM golang:1.17-alpine

USER root

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

COPY ca-certificates.crt /etc/ssl/certs/
COPY traefik /usr/sbin
EXPOSE 80 8080 4443

VOLUME ["/tmp"]

ENTRYPOINT ["/entrypoint.sh", "traefik"]
CMD ["--api.insecure", \
     "--accesslog", \
     "--entrypoints.web.Address=:8000", \
     "--entrypoints.websecure.Address=:4443", \
     "--providers.kubernetescrd"